aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Models/Bid.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace vglinskii.aspNet.MvcCreditApp1.Models
{
    public class Bid
    {
        // ID заявки
        public virtual int BidId { get; set; }
        // Имя заявителя
        [DisplayName("Имя заявителя")]
        public virtual string Name { get; set; }
        // Название кредита
        [DisplayName("Название кредита")]

        public virtual string CreditHead { get; set; }
        // Дата подачи заявки
        [DisplayName("Дата подачи заявки")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}")]

        public virtual DateTime bidDate { get; set; }
    }
}

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Models/Credit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace vglinskii.aspNet.MvcCreditApp1.Models
{
    public class Credit
    {

            // ID кредита
            public virtual int CreditId { get; set; }
            // Название
            public virtual string Head { get; set; }
            // Период, на который выдается кредит
            public virtual int Period { get; set; }
            // Максимальная сумма кредита
            public virtual int Sum { get; set; }
            // Процентная ставка
            public virtual int Procent { get; set; }
        }
    }

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Models/CreditContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace vglinskii.aspNet.MvcCreditApp1.Models
{
    public class CreditContext : DbContext
    {
        public DbSet<Credit> Credits { get; set; }
        public DbSet<Bid> Bids { get; set; }
    }
}

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Models/CreditsDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace vglinskii.aspNet.MvcCreditApp1.Models
{
    public class CreditsDbInitializer : DropCreateDatabaseIfModelChanges<CreditContext>
    {

        protected override void Seed(CreditContext context)
        {
            context.Credits.Add(new Credit
            {
                Head = "Ипотечный кредит",
                Period = 10,
                Sum = 1000000,
                Procent = 15
            });
            context.Credits.Add(new Credit
            {
                Head = "Образовательный кредит",
                Period = 7,
                Sum = 300000,
                Procent = 10
            });
            context.Credits.Add(new Credit
            {
                Head = "Потребительский кредит",
                Period = 5,
                Sum = 500000,
                Procent = 19
            });
            base.Seed(context);
        }
    }
}

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Controllers/CreditsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using vglinskii.aspNet.MvcCreditApp1.Models;

namespace vglinskii.aspNet.MvcCreditApp1.Controllers
{
    public class CreditsController : Controller
    {
        private CreditContext db = new CreditContext();

        // GET: Credits
        public ActionResult Index()
        {
            return View(db.Credits.ToList());
        }

        // GET: Credits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Credit credit = db.Credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            return View(credit);
        }

        // GET: Credits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Credits/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CreditId,Head,Period,Sum,Procent")] Credit credit)
        {
            if (ModelState.IsValid)
            {
                db.Credits.Add(credit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(credit);
        }

        // GET: Credits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Credit credit = db.Credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            return View(credit);
        }

        // POST: Credits/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CreditId,Head,Period,Sum,Procent")] Credit credit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(credit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(credit);
        }

        // GET: Credits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Credit credit = db.Credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            return View(credit);
        }

        // POST: Credits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Credit credit = db.Credits.Find(id);
            db.Credits.Remove(credit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vglinskii.aspNet.MvcCreditApp1.Models;

namespace vglinskii.aspNet.MvcCreditApp1.Controllers
{
    public class HomeController : Controller
    {
        private CreditContext db = new CreditContext();
        public ActionResult Index()
        {
            GiveCredits();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        private void GiveCredits()
        {
            var allCredits = db.Credits.ToList<Credit>();
            ViewBag.Credits = allCredits;
        }

        [HttpGet]
        public ActionResult CreateBid()
        {
            GiveCredits();
            var allBids = db.Bids.ToList<Bid>();
            ViewBag.Bids = allBids;
            return View();
        }

        [HttpPost]
        public string CreateBid(Bid newBid)
        {
            newBid.bidDate = DateTime.Now;
            // Добавляем новую заявку в БД
            db.Bids.Add(newBid);
            // Сохраняем в БД все изменения
            db.SaveChanges();
            return "Спасибо, <b>" + newBid.Name + "</b>, за выбор нашего банка. Ваша заявка будет рассмотрена в течении 10 дней.";
 }

    }
}

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Bids/Create.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Bid

@{
    ViewBag.Title = "Создание заявки";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание заявки</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bid</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditHead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditHead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditHead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bidDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bidDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bidDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться в список", "Index")
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Bids/Delete.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Bid

@{
    ViewBag.Title = "Удалить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удалить</h2>

<h3>Вы уверенны?</h3>
<div>
    <h4>Bid</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditHead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditHead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bidDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bidDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Bids/Details.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Bid

@{
    ViewBag.Title = "Подробная информация";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Подробная информация</h2>

<div>
    <h4>Bid</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditHead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditHead)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bidDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bidDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.BidId }) |
    @Html.ActionLink("Вернуться в список", "Index")
</p>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Bids/Edit.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Bid

@{
    ViewBag.Title = "Изменить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Изменить</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bid</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BidId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditHead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditHead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditHead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bidDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bidDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bidDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться в список", "Index")
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Bids/Index.cshtml
@model IEnumerable<vglinskii.aspNet.MvcCreditApp1.Models.Bid>

@{
    ViewBag.Title = "Заявки";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Заявки</h2>

<p>
    @Html.ActionLink("Создать новую заявку", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreditHead)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bidDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreditHead)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bidDate)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id=item.BidId }) |
            @Html.ActionLink("Подробнее", "Details", new { id=item.BidId }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.BidId })
        </td>
    </tr>
}

</table>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Credits/Create.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Credit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Credit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Head, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Head, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Head, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Procent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Procent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Procent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Credits/Delete.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Credit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Credit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Head)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Head)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Credits/Details.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Credit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Credit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Head)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Head)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procent)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CreditId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Credits/Edit.cshtml
@model vglinskii.aspNet.MvcCreditApp1.Models.Credit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Credit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CreditId)

        <div class="form-group">
            @Html.LabelFor(model => model.Head, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Head, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Head, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Procent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Procent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Procent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Credits/Index.cshtml
@model IEnumerable<vglinskii.aspNet.MvcCreditApp1.Models.Credit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Head)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Period)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Procent)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Head)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Period)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Procent)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CreditId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CreditId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CreditId })
        </td>
    </tr>
}

</table>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

aspNetCourse/ASP.NET.MVC/lab6/vglinskii.aspNet.MvcCreditApp1/vglinskii.aspNet.MvcCreditApp1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Информация", "About", "Home")</li>
                    <li>@Html.ActionLink("Послать заявку", "CreateBid", "Home")</li>
                    <li>@Html.ActionLink("Просмотреть заявки", "Index", "Bids")</li>
                    <li>@Html.ActionLink("Кредиты", "Index", "Credits")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>